# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  aspapi:
    # image: aspapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - 8081:5000
    # expose: 
    #   - 8081
    depends_on:
      - sql_server

  sql_server:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "http://localhost:1433", "-U", "sa", "-P", "ourStrong@Passw0rd", "-Q", "SELECT 1", "||", "exit 1"]
    # container_name: sql_server_container
    build:
      context: .
      # dockerfile: Mssql.Dockerfile
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      SSQL_PID: "Express"
    ports:
      - 1433:1433
    expose:
      - 1433

    volumes:
      - ./sql_server_vol_data:/var/opt/mssql/data





