# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  asp_api:
    container_name: asp_api
    build:
      context: .
      dockerfile: ./slim.Dockerfile
    environment: 
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /home/dev/deploy_volumes/asp_api_data:/wwwroot

volumes:
  sql_server_data:
      # external: true
  





