# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  aspapi:
    image: aspapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:80

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433



