// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace asp_api.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210723012030_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sa@angular.io",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Brieuc_Moreau73@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Marion_Faure@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Firmin.Bertrand@yahoo.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Aurelle.Brunet5@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Victoire_Carpentier54@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Nathan46@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Herve1@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Anstrudie.Breton@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Fantin_Pierre51@gmail.com",
                            Password = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
