// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace asp_api.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210717143122_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sa@angular.io",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Robert.Martin@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Aquilin.Laurent@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Gontran5@yahoo.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Agneflete66@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Jeanne_Barre44@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Aurore_Simon14@hotmail.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Christian67@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Athanasie.Colin21@yahoo.fr",
                            Password = "123"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Pascal26@hotmail.fr",
                            Password = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
